name: Deploy GitBook

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm install -g gitbook-cli
        npm install
        
    - name: Install GitBook plugins
      run: gitbook install
      
    - name: Build GitBook
      run: gitbook build
      
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_book
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v3
      with:
        name: gitbook-build
        path: _book/